modLoader = "javafml"
loaderVersion = "[50,)"
issueTrackerURL = "https://github.com/dzwdz/chat_heads/issues"
license = "MPL-2.0"

[[mods]]
modId = "chat_heads"
version = "${mod_version}"
displayName = "Chat Heads"
authors = "dzwdz, Fourmisain"

description = '''
See who are you chatting with!
This mod adds player heads next to their chat messages.
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.chat_heads]]
modId = "forge"
mandatory = true
versionRange = "[50.1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chat_heads]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_game_version_range}"
ordering = "NONE"
side = "CLIENT"
